// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/empower1.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Block struct {
	Hash                 []byte         `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	PrevHash             []byte         `protobuf:"bytes,2,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	Timestamp            uint64         `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,4,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Validator            []byte         `protobuf:"bytes,5,opt,name=validator,proto3" json:"validator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_92feacf6d2582039, []int{0}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Block) GetPrevHash() []byte {
	if m != nil {
		return m.PrevHash
	}
	return nil
}

func (m *Block) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Block) GetValidator() []byte {
	if m != nil {
		return m.Validator
	}
	return nil
}

type Transaction struct {
	Hash                 []byte      `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Inputs               []*TxInput  `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs              []*TxOutput `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_92feacf6d2582039, []int{1}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Transaction) GetInputs() []*TxInput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *Transaction) GetOutputs() []*TxOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type TxInput struct {
	PrevTxHash           []byte   `protobuf:"bytes,1,opt,name=prev_tx_hash,json=prevTxHash,proto3" json:"prev_tx_hash,omitempty"`
	OutputIndex          uint32   `protobuf:"varint,2,opt,name=output_index,json=outputIndex,proto3" json:"output_index,omitempty"`
	ScriptSig            []byte   `protobuf:"bytes,3,opt,name=script_sig,json=scriptSig,proto3" json:"script_sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxInput) Reset()         { *m = TxInput{} }
func (m *TxInput) String() string { return proto.CompactTextString(m) }
func (*TxInput) ProtoMessage()    {}
func (*TxInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_92feacf6d2582039, []int{2}
}

func (m *TxInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxInput.Unmarshal(m, b)
}
func (m *TxInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxInput.Marshal(b, m, deterministic)
}
func (m *TxInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxInput.Merge(m, src)
}
func (m *TxInput) XXX_Size() int {
	return xxx_messageInfo_TxInput.Size(m)
}
func (m *TxInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TxInput.DiscardUnknown(m)
}

var xxx_messageInfo_TxInput proto.InternalMessageInfo

func (m *TxInput) GetPrevTxHash() []byte {
	if m != nil {
		return m.PrevTxHash
	}
	return nil
}

func (m *TxInput) GetOutputIndex() uint32 {
	if m != nil {
		return m.OutputIndex
	}
	return 0
}

func (m *TxInput) GetScriptSig() []byte {
	if m != nil {
		return m.ScriptSig
	}
	return nil
}

type TxOutput struct {
	Value                uint64   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	ScriptPubKey         []byte   `protobuf:"bytes,2,opt,name=script_pub_key,json=scriptPubKey,proto3" json:"script_pub_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxOutput) Reset()         { *m = TxOutput{} }
func (m *TxOutput) String() string { return proto.CompactTextString(m) }
func (*TxOutput) ProtoMessage()    {}
func (*TxOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_92feacf6d2582039, []int{3}
}

func (m *TxOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxOutput.Unmarshal(m, b)
}
func (m *TxOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxOutput.Marshal(b, m, deterministic)
}
func (m *TxOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxOutput.Merge(m, src)
}
func (m *TxOutput) XXX_Size() int {
	return xxx_messageInfo_TxOutput.Size(m)
}
func (m *TxOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_TxOutput.DiscardUnknown(m)
}

var xxx_messageInfo_TxOutput proto.InternalMessageInfo

func (m *TxOutput) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *TxOutput) GetScriptPubKey() []byte {
	if m != nil {
		return m.ScriptPubKey
	}
	return nil
}

type UTXO struct {
	TxHash               []byte    `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	OutputIndex          uint32    `protobuf:"varint,2,opt,name=output_index,json=outputIndex,proto3" json:"output_index,omitempty"`
	Output               *TxOutput `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UTXO) Reset()         { *m = UTXO{} }
func (m *UTXO) String() string { return proto.CompactTextString(m) }
func (*UTXO) ProtoMessage()    {}
func (*UTXO) Descriptor() ([]byte, []int) {
	return fileDescriptor_92feacf6d2582039, []int{4}
}

func (m *UTXO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UTXO.Unmarshal(m, b)
}
func (m *UTXO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UTXO.Marshal(b, m, deterministic)
}
func (m *UTXO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UTXO.Merge(m, src)
}
func (m *UTXO) XXX_Size() int {
	return xxx_messageInfo_UTXO.Size(m)
}
func (m *UTXO) XXX_DiscardUnknown() {
	xxx_messageInfo_UTXO.DiscardUnknown(m)
}

var xxx_messageInfo_UTXO proto.InternalMessageInfo

func (m *UTXO) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *UTXO) GetOutputIndex() uint32 {
	if m != nil {
		return m.OutputIndex
	}
	return 0
}

func (m *UTXO) GetOutput() *TxOutput {
	if m != nil {
		return m.Output
	}
	return nil
}

type Account struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance              uint64   `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_92feacf6d2582039, []int{5}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Account) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func init() {
	proto.RegisterType((*Block)(nil), "empower1.Block")
	proto.RegisterType((*Transaction)(nil), "empower1.Transaction")
	proto.RegisterType((*TxInput)(nil), "empower1.TxInput")
	proto.RegisterType((*TxOutput)(nil), "empower1.TxOutput")
	proto.RegisterType((*UTXO)(nil), "empower1.UTXO")
	proto.RegisterType((*Account)(nil), "empower1.Account")
}

func init() {
	proto.RegisterFile("proto/empower1.proto", fileDescriptor_92feacf6d2582039)
}

var fileDescriptor_92feacf6d2582039 = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcf, 0x0f, 0x93, 0x30,
	0x14, 0x0e, 0x1b, 0x83, 0xed, 0x0d, 0x4d, 0x6c, 0x66, 0x24, 0x51, 0x13, 0x24, 0x3b, 0x4c, 0x63,
	0x66, 0xd4, 0x93, 0x07, 0x0f, 0xee, 0x60, 0x5c, 0x3c, 0xcc, 0xd4, 0x99, 0x18, 0x2f, 0xa4, 0x40,
	0xb3, 0x35, 0x03, 0x4a, 0x68, 0x99, 0xcc, 0x7f, 0xca, 0x7f, 0xd1, 0xf0, 0x80, 0xc1, 0x92, 0x1d,
	0x3c, 0xd1, 0xef, 0x47, 0xdf, 0xf7, 0xe5, 0x51, 0x58, 0xe4, 0x85, 0xd4, 0xf2, 0x0d, 0x4f, 0x73,
	0xf9, 0x9b, 0x17, 0x6f, 0xd7, 0x08, 0xc9, 0xb4, 0xc3, 0xfe, 0x5f, 0x03, 0x26, 0x9b, 0x44, 0x46,
	0x27, 0x42, 0xc0, 0x3c, 0x32, 0x75, 0x74, 0x0d, 0xcf, 0x58, 0x39, 0x14, 0xcf, 0xe4, 0x29, 0xcc,
	0xf2, 0x82, 0x9f, 0x03, 0x14, 0x46, 0x28, 0x4c, 0x6b, 0xe2, 0x4b, 0x2d, 0x3e, 0x83, 0x99, 0x16,
	0x29, 0x57, 0x9a, 0xa5, 0xb9, 0x3b, 0xf6, 0x8c, 0x95, 0x49, 0x7b, 0x82, 0x7c, 0x00, 0x47, 0x17,
	0x2c, 0x53, 0x2c, 0xd2, 0x42, 0x66, 0xca, 0x35, 0xbd, 0xf1, 0x6a, 0xfe, 0xee, 0xf1, 0xfa, 0xda,
	0x64, 0xdf, 0xab, 0xf4, 0xc6, 0x5a, 0x0f, 0x3e, 0xb3, 0x44, 0xc4, 0x4c, 0xcb, 0xc2, 0x9d, 0x60,
	0x6a, 0x4f, 0xf8, 0x7f, 0x60, 0x3e, 0xb8, 0x7a, 0xb7, 0xf6, 0x4b, 0xb0, 0x44, 0x96, 0x97, 0x5a,
	0xb9, 0x23, 0x4c, 0x7d, 0x34, 0x48, 0xad, 0xb6, 0xb5, 0x42, 0x5b, 0x03, 0x79, 0x0d, 0xb6, 0x2c,
	0x35, 0x7a, 0xc7, 0xe8, 0x25, 0x43, 0xef, 0x0e, 0x25, 0xda, 0x59, 0xfc, 0x14, 0xec, 0x76, 0x00,
	0xf1, 0xc0, 0xc1, 0xd5, 0xe8, 0x2a, 0x18, 0xe4, 0x43, 0xcd, 0xed, 0x2b, 0xdc, 0xcf, 0x0b, 0x70,
	0x9a, 0x7b, 0x81, 0xc8, 0x62, 0x5e, 0xe1, 0xfe, 0x1e, 0xd0, 0x79, 0xc3, 0x6d, 0x6b, 0x8a, 0x3c,
	0x07, 0x50, 0x51, 0x21, 0x72, 0x1d, 0x28, 0x71, 0xc0, 0x1d, 0x3a, 0x74, 0xd6, 0x30, 0xdf, 0xc5,
	0xc1, 0xff, 0x0c, 0xd3, 0xae, 0x03, 0x59, 0xc0, 0xe4, 0xcc, 0x92, 0x92, 0x63, 0x90, 0x49, 0x1b,
	0x40, 0x96, 0xf0, 0xb0, 0x1d, 0x90, 0x97, 0x61, 0x70, 0xe2, 0x97, 0xf6, 0x2f, 0x39, 0x0d, 0xfb,
	0xad, 0x0c, 0xbf, 0xf2, 0x8b, 0x9f, 0x81, 0xf9, 0x63, 0xff, 0x73, 0x47, 0x9e, 0x80, 0x7d, 0x5b,
	0xd7, 0xd2, 0xff, 0x5d, 0xf5, 0x15, 0x58, 0x0d, 0xc4, 0x9a, 0xf7, 0xf7, 0xd4, 0x3a, 0xfc, 0x8f,
	0x60, 0x7f, 0x8a, 0x22, 0x59, 0x66, 0x9a, 0xb8, 0x60, 0xb3, 0x38, 0x2e, 0xb8, 0x52, 0x6d, 0x64,
	0x07, 0x6b, 0x25, 0x64, 0x09, 0xcb, 0x22, 0x8e, 0x71, 0x26, 0xed, 0xe0, 0x66, 0xf9, 0xcb, 0x3f,
	0x08, 0x7d, 0x2c, 0xc3, 0x75, 0x24, 0xd3, 0xeb, 0xd3, 0xed, 0x0f, 0xf8, 0x86, 0x43, 0x0b, 0x3f,
	0xef, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x86, 0xb5, 0xb8, 0xd0, 0xe2, 0x02, 0x00, 0x00,
}
